package com.aliyun.gumiho.sql.enums;

/**
 * @author kongtong.ouyang on 2018/5/9.
 */
public enum SQLObjectType {


    SET_CHARACTER_SET,
    SET_CHARSET,
    SET_DEFAULT_ROLE,
    SET_NAMES,
    SET_PASSWORD,
    SET,

    CREATE_ANALYTIC,
    ALTER_ANALYTIC,
    DROP_ANALYTIC,

    COMMENT,

    CREATE_DATABASE,
    ALTER_DATABASE,
    DROP_DATABASE,

    CREATE_DATABASE_LINK,
    ALTER_DATABASE_LINK,
    DROP_DATABASE_LINK,

    CREATE_DOMAIN,
    ALTER_DOMAIN,
    DROP_DOMAIN,

    CREATE_EVENT,
    ALTER_EVENT,
    DROP_EVENT,

    CREATE_FUNCTION,
    ALTER_FUNCTION,
    DROP_FUNCTION,

    CREATE_INDEX,
    ALTER_INDEX,
    DROP_INDEX,

    CREATE_MATERIALIZED_VIEW,
    ALTER_MATERIALIZED_VIEW,
    DROP_MATERIALIZED_VIEW,

    CREATE_MATERIALIZED_VIEW_LOG,
    ALTER_MATERIALIZED_VIEW_LOG,
    DROP_MATERIALIZED_VIEW_LOG,

    CREATE_PACKAGE,
    ALTER_PACKAGE,
    DROP_PACKAGE,

    CREATE_PACKAGE_BODY,
    ALTER_PACKAGE_BODY,
    DROP_PACKAGE_BODY,

    CREATE_PLUGGABLE_DATABASE,
    ALTER_PLUGGABLE_DATABASE,
    DROP_PLUGGABLE_DATABASE,

    CREATE_PROCEDURE,
    ALTER_PROCEDURE,
    DROP_PROCEDURE,

    CREATE_ROLE,
    ALTER_ROLE,
    DROP_ROLE,

    CREATE_ROLLBACK_SEGMENT,
    ALTER_ROLLBACK_SEGMENT,
    DROP_ROLLBACK_SEGMENT,

    CREATE_SCHEMA,
    ALTER_SCHEMA,
    DROP_SCHEMA,

    CREATE_SEQUENCE,
    ALTER_SEQUENCE,
    DROP_SEQUENCE,

    CREATE_SERVER,
    ALTER_SERVER,
    DROP_SERVER,

    CREATE_SYNONYM,
    ALTER_SYNONYM,
    DROP_SYNONYM,

    CREATE_TABLE,
    ALTER_TABLE,
    DROP_TABLE,

    CREATE_TABLESPACE,
    ALTER_TABLESPACE,
    DROP_TABLESPACE,

    CREATE_TRIGGER,
    ALTER_TRIGGER,
    DROP_TRIGGER,

    CREATE_TYPE,
    ALTER_TYPE,
    DROP_TYPE,

    CREATE_TYPE_BODY,
    ALTER_TYPE_BODY,
    DROP_TYPE_BODY,

    CREATE_USER,
    ALTER_USER,
    DROP_USER,

    CREATE_VIEW,
    ALTER_VIEW,
    DROP_VIEW,



    CALL,
    DO,
    HANDLER,
    LOAD_DATA,
    LOAD_XML,

    LOCK_TABLE,
    UNLOCK_TABLE,
    RENAME_TABLE,
    TRUNCATE_TABLE,
    REPLACE,

    INSERT,
    DELETE,
    UPDATE,
    SELECT,
    SELECT_INTO,

    CASE,
    CLOSE,
    CONTINUE,
    EXIT,
    FETCH,
    FOR_ALL,
    FOR_LOOP,
    GO_TO,
    IF,
    ITERATE,
    LEAVE,
    LOOP,
    MERGE,
    NULL,
    OPEN_FOR,
    OPEN,
    PIPE_ROW,
    RAISE,
    REPEAT,
    RETURN,
    WHILE_LOOP,
    WHILE,

    ALTER_SESSION,

    SET_ROLE,

    COMMIT,
    RELEASE_SAVEPOINT,
    ROLLBACK,
    SAVEPOINT,
    SET_CONSTRAINTS,
    SET_CONSTRAINT,
    SET_TRANSACTION,

    EXPLAIN,
    USE,

    EXPR;
}
